server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sim_demon?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Loveme1314
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demon-main
# # redis缓存服务配置
#    session:
#        store-type: redis
#    # Redis数据库索引（默认为0）
#    redis:
#        database: 1
#        # Redis服务器地址
#        host: 127.0.0.1
#        # Redis服务器连接端口
#        port: 6379
#        # Redis服务器连接密码（默认为空）
#        password: 123456
#        # 连接池最大连接数（使用负值表示没有限制）
#        pool:
#            maxActive: 8
#            # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            maxWait: -1
#            # 连接池中的最大空闲连接
#            maxIdle: 8
#            # 连接池中的最小空闲连接
#            minIdle: 0
#        # 连接超时时间（毫秒）
#        timeout: 0
#        # 默认的数据过期时间，主要用于shiro权限管理
#        expire: 2592000
